// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createTransitionOrIncrement = `-- name: CreateTransitionOrIncrement :exec
INSERT INTO transitions (word_id, next_id)
VALUES (?, ?)
ON CONFLICT (word_id, next_id) DO UPDATE 
    SET count = count + 1
`

type CreateTransitionOrIncrementParams struct {
	WordID int64
	NextID int64
}

func (q *Queries) CreateTransitionOrIncrement(ctx context.Context, arg CreateTransitionOrIncrementParams) error {
	_, err := q.db.ExecContext(ctx, createTransitionOrIncrement, arg.WordID, arg.NextID)
	return err
}

const createWord = `-- name: CreateWord :one
INSERT INTO words (word)
VALUES (?)
ON CONFLICT (word) DO UPDATE
    SET word = excluded.word
RETURNING id
`

func (q *Queries) CreateWord(ctx context.Context, word string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createWord, word)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAllWords = `-- name: GetAllWords :many
SELECT id, word FROM words
`

func (q *Queries) GetAllWords(ctx context.Context) ([]Word, error) {
	rows, err := q.db.QueryContext(ctx, getAllWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(&i.ID, &i.Word); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransitions = `-- name: GetTransitions :many
SELECT id, word_id, next_id, count, probability FROM transitions
WHERE word_id = ?
`

func (q *Queries) GetTransitions(ctx context.Context, wordID int64) ([]Transition, error) {
	rows, err := q.db.QueryContext(ctx, getTransitions, wordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transition
	for rows.Next() {
		var i Transition
		if err := rows.Scan(
			&i.ID,
			&i.WordID,
			&i.NextID,
			&i.Count,
			&i.Probability,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWord = `-- name: GetWord :one
SELECT id, word FROM words
WHERE id = ?
`

func (q *Queries) GetWord(ctx context.Context, id int64) (Word, error) {
	row := q.db.QueryRowContext(ctx, getWord, id)
	var i Word
	err := row.Scan(&i.ID, &i.Word)
	return i, err
}

const getWordId = `-- name: GetWordId :one
SELECT id FROM words
WHERE word = ?
LIMIT 1
`

func (q *Queries) GetWordId(ctx context.Context, word string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWordId, word)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setTransitionProbability = `-- name: SetTransitionProbability :exec
UPDATE transitions
SET probability = ?
WHERE id = ?
`

type SetTransitionProbabilityParams struct {
	Probability float64
	ID          int64
}

func (q *Queries) SetTransitionProbability(ctx context.Context, arg SetTransitionProbabilityParams) error {
	_, err := q.db.ExecContext(ctx, setTransitionProbability, arg.Probability, arg.ID)
	return err
}
