// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

type Probability struct {
	ID           int64
	GuildID      string
	TransitionID int64
	Count        int64
	Probability  float64
}

type Transition struct {
	ID     int64
	WordID int64
	NextID int64
}

type Word struct {
	ID   int64
	Word string
}
