// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

type Count struct {
	ID           int64
	GuildID      string
	TransitionID int64
	Count        int64
	Modifier     float64
}

type Transition struct {
	ID     int64
	WordID int64
	NextID int64
}

type Word struct {
	ID   int64
	Word string
}
