// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
)

const createTransition = `-- name: CreateTransition :one
INSERT INTO transitions (word_id, next_id)
VALUES (?, ?)
ON CONFLICT(word_id, next_id) DO UPDATE
SET word_id = transitions.word_id
RETURNING id
`

type CreateTransitionParams struct {
	WordID int64
	NextID int64
}

func (q *Queries) CreateTransition(ctx context.Context, arg CreateTransitionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTransition, arg.WordID, arg.NextID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createWord = `-- name: CreateWord :one
INSERT INTO words (word)
VALUES (?)
ON CONFLICT(word) DO UPDATE
    SET word = excluded.word
RETURNING id
`

func (q *Queries) CreateWord(ctx context.Context, word string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createWord, word)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAllWords = `-- name: GetAllWords :many
SELECT id, word FROM words
`

func (q *Queries) GetAllWords(ctx context.Context) ([]Word, error) {
	rows, err := q.db.QueryContext(ctx, getAllWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(&i.ID, &i.Word); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProbablities = `-- name: GetProbablities :many
SELECT p.id, p.guild_id, p.transition_id, p.count, p.probability, t.next_id
FROM probabilities p
INNER JOIN transitions t ON t.id = p.transition_id
WHERE p.guild_id = ? AND t.word_id = ?
`

type GetProbablitiesParams struct {
	GuildID string
	WordID  int64
}

type GetProbablitiesRow struct {
	ID           int64
	GuildID      string
	TransitionID int64
	Count        int64
	Probability  float64
	NextID       int64
}

func (q *Queries) GetProbablities(ctx context.Context, arg GetProbablitiesParams) ([]GetProbablitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, getProbablities, arg.GuildID, arg.WordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProbablitiesRow
	for rows.Next() {
		var i GetProbablitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.TransitionID,
			&i.Count,
			&i.Probability,
			&i.NextID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWord = `-- name: GetWord :one
SELECT id, word FROM words
WHERE id = ?
`

func (q *Queries) GetWord(ctx context.Context, id int64) (Word, error) {
	row := q.db.QueryRowContext(ctx, getWord, id)
	var i Word
	err := row.Scan(&i.ID, &i.Word)
	return i, err
}

const getWordId = `-- name: GetWordId :one
SELECT id FROM words
WHERE word = ?
LIMIT 1
`

func (q *Queries) GetWordId(ctx context.Context, word string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWordId, word)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const incrementTransitionCount = `-- name: IncrementTransitionCount :exec
INSERT INTO probabilities (guild_id, transition_id)
VALUES (?, ?)
ON CONFLICT(guild_id, transition_id) DO UPDATE
SET count = count + 1
`

type IncrementTransitionCountParams struct {
	GuildID      string
	TransitionID int64
}

func (q *Queries) IncrementTransitionCount(ctx context.Context, arg IncrementTransitionCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementTransitionCount, arg.GuildID, arg.TransitionID)
	return err
}

const setProbability = `-- name: SetProbability :exec
UPDATE probabilities 
SET probability = ?
WHERE id = ?
`

type SetProbabilityParams struct {
	Probability float64
	ID          int64
}

func (q *Queries) SetProbability(ctx context.Context, arg SetProbabilityParams) error {
	_, err := q.db.ExecContext(ctx, setProbability, arg.Probability, arg.ID)
	return err
}
