// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
)

const addTransition = `-- name: AddTransition :one
INSERT INTO transitions (word_id, next_id)
VALUES (?, ?)
ON CONFLICT(word_id, next_id) DO UPDATE
SET word_id = transitions.word_id
RETURNING id
`

type AddTransitionParams struct {
	WordID int64
	NextID int64
}

func (q *Queries) AddTransition(ctx context.Context, arg AddTransitionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addTransition, arg.WordID, arg.NextID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addWord = `-- name: AddWord :one
INSERT INTO words (word)
VALUES (?)
ON CONFLICT(word) DO UPDATE
    SET word = excluded.word
RETURNING id
`

func (q *Queries) AddWord(ctx context.Context, word string) (int64, error) {
	row := q.db.QueryRowContext(ctx, addWord, word)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAllWords = `-- name: GetAllWords :many
SELECT id, word FROM words
`

func (q *Queries) GetAllWords(ctx context.Context) ([]Word, error) {
	rows, err := q.db.QueryContext(ctx, getAllWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(&i.ID, &i.Word); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCounts = `-- name: GetCounts :many
SELECT c.id, c.guild_id, c.transition_id, c.count, c.modifier, t.next_id
FROM counts c
INNER JOIN transitions t ON t.id = c.transition_id
WHERE c.guild_id = ? AND t.word_id = ?
`

type GetCountsParams struct {
	GuildID string
	WordID  int64
}

type GetCountsRow struct {
	ID           int64
	GuildID      string
	TransitionID int64
	Count        int64
	Modifier     float64
	NextID       int64
}

func (q *Queries) GetCounts(ctx context.Context, arg GetCountsParams) ([]GetCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCounts, arg.GuildID, arg.WordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCountsRow
	for rows.Next() {
		var i GetCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.TransitionID,
			&i.Count,
			&i.Modifier,
			&i.NextID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWord = `-- name: GetWord :one
SELECT id, word FROM words
WHERE id = ?
`

func (q *Queries) GetWord(ctx context.Context, id int64) (Word, error) {
	row := q.db.QueryRowContext(ctx, getWord, id)
	var i Word
	err := row.Scan(&i.ID, &i.Word)
	return i, err
}

const getWordID = `-- name: GetWordID :one
SELECT id FROM words
WHERE word = ?
LIMIT 1
`

func (q *Queries) GetWordID(ctx context.Context, word string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWordID, word)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const incrementCount = `-- name: IncrementCount :exec
INSERT INTO counts (guild_id, transition_id)
VALUES (?, ?)
ON CONFLICT(guild_id, transition_id) DO UPDATE
SET count = count + 1
`

type IncrementCountParams struct {
	GuildID      string
	TransitionID int64
}

func (q *Queries) IncrementCount(ctx context.Context, arg IncrementCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementCount, arg.GuildID, arg.TransitionID)
	return err
}
